version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - nginx_data:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.nginx-test.loadbalancer.server.port=80"
      restart_policy:
        condition: on-failure
    networks:
      - nginx_network

  nginx-helper:
    image: alpine:latest
    command: |
      sh -c "echo '<h1>Hello from Nginx Swarm Stack!</h1><p>Port: ${NGINX_PORT:-8080}</p>' > /html/index.html && sleep 10"
    volumes:
      - nginx_data:/html
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - nginx_network

volumes:
  nginx_data:

networks:
  nginx_network:
    driver: overlay
